[workspace]
resolver = "2"

default-members = [
    "t5f_base",
    "t5f_client",
    "t5f_common",
    "t5f_net",
    "t5f_server",
    "t5f_utility",
]

members = [
    "t5f_base",
    "t5f_client",
    "t5f_common",
    "t5f_net",
    "t5f_server",
    "t5f_utility",
]

[profile.dev.package."*"]
opt-level = 3